/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#1a73e8',
        'primary-hover': '#1557b0',
        'text-primary': '#202124',
        'text-secondary': '#5f6368',
        'border-color': '#dadce0',
      },
      fontFamily: {
        sans: ['Google Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
} rimary': '#1a73e8',
        'primary-hover': '#1557b0',
        'primary-container': '#d3e3fd',
        'on-primary': '#ffffff',
        'on-primary-container': '#001d3d',
        'secondary': '#5c6bc0',
        'secondary-hover': '#3f51b5',
        'secondary-container': '#e8eaf6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#1a237e',
        'surface': '#ffffff',
        'surface-variant': '#f5f5f5',
        'surface-container': '#f8f9fa',
        'surface-container-high': '#f1f3f4',
        'on-surface': '#202124',
        'on-surface-variant': '#5f6368',
        'background': '#ffffff',
        'background-variant': '#f8f9fa',
        'on-background': '#202124',
        'error': '#d93025',
        'error-container': '#fce8e6',
        'on-error': '#ffffff',
        'on-error-container': '#410e0b',
        'success': '#188038',
        'success-container': '#e6f4ea',
        'on-success': '#ffffff',
        'on-success-container': '#0d652d',
        'border-color': '#dadce0',
        'border-color-variant': '#e8eaed',
        'text-primary': '#202124',
        'text-secondary': '#5f6368',
        'text-tertiary': '#80868b',
        'text-disabled': '#bdc1c6',
      },
      boxShadow: {
        'elevation-1': '0 1px 2px 0 rgba(0, 0, 0, 0.1)',
        'elevation-2': '0 2px 4px 0 rgba(0, 0, 0, 0.1)',
        'elevation-3': '0 4px 8px 0 rgba(0, 0, 0, 0.1)',
        'elevation-4': '0 8px 16px 0 rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
}
